ivy_checks :
	ivy_check trace=true 2s11_d22_f11s_f12e.ivy > tests/2s11_d22_f11s_f12e_trace.txt 
	ivy_check trace=true 2s11_d23_f11w_f21n.ivy > tests/2s11_d23_f11w_f21n_trace.txt 
	ivy_check trace=true 2s11_d32_f11s_f12e.ivy > tests/2s11_d32_f11s_f12e_trace.txt 
	ivy_check trace=true 2s12_d22_f11s_f12e.ivy > tests/2s12_d22_f11s_f12e_trace.txt 
	ivy_check trace=true 2s12_d23_f12s_f13e.ivy > tests/2s12_d23_f12s_f13e_trace.txt 
	ivy_check trace=true 2s12_d32_f11s_f12e.ivy > tests/2s12_d32_f11s_f12e_trace.txt 
	ivy_check trace=true 2s13_d22_f11s_f12e.ivy > tests/2s13_d22_f11s_f12e_trace.txt 
	ivy_check trace=true 2s13_d23_f12s_f13e.ivy > tests/2s13_d23_f12s_f13e_trace.txt 
	ivy_check trace=true 2s13_d32_f11s_f12e.ivy > tests/2s13_d32_f11s_f12e_trace.txt 
	ivy_check trace=true 2s21_d23_f11w_f21n.ivy > tests/2s21_d23_f11w_f21n_trace.txt 
	ivy_check trace=true 2s21_d32_f21s_f22e.ivy > tests/2s21_d32_f21s_f22e_trace.txt 
	ivy_check trace=true 2s21_d33_f21w_f31n.ivy > tests/2s21_d33_f21w_f31n_trace.txt 
	ivy_check trace=true 2s22_d32_f21s_f22e.ivy > tests/2s22_d32_f21s_f22e_trace.txt 
	ivy_check trace=true 2s23_d32_f21s_f22e.ivy > tests/2s23_d32_f21s_f22e_trace.txt 
	ivy_check trace=true 2s31_d23_f11w_f21n.ivy > tests/2s31_d23_f11w_f21n_trace.txt 
	ivy_check trace=true 2s31_d33_f21w_f31n.ivy > tests/2s31_d33_f21w_f31n_trace.txt 
