checks: 
	$(MAKE) -C corner_ne checks
	$(MAKE) -C corner_nw checks
	$(MAKE) -C corner_se checks
	$(MAKE) -C corner_sw checks
	$(MAKE) -C edge_e checks
	$(MAKE) -C edge_n checks
	$(MAKE) -C edge_s checks
	$(MAKE) -C edge_w checks
	$(MAKE) -C middle checks
