ivy_checks :
	ivy_check trace=true corner_ne.ivy > corner_ne.txt
	ivy_check trace=true corner_nw.ivy > corner_nw.txt
	ivy_check trace=true corner_se.ivy > corner_se.txt
	ivy_check trace=true corner_sw.ivy > corner_sw.txt
	ivy_check trace=true edge_n.ivy > edge_n.txt
	ivy_check trace=true edge_e.ivy > edge_e.txt
	ivy_check trace=true edge_s.ivy > edge_s.txt
	ivy_check trace=true edge_w.ivy > edge_w.txt
	ivy_check trace=true middle.ivy > middle.txt