#lang ivy1.7

object intf = {
	action send
	action recv
	action reset
} #end intf

type place = {a,b,c,recv}

object spec = {
	individual flit_is : place
	
	after init {
		flit_is := a;
	}
	
	before intf.send {
		assert flit_is = a | flit_is = b | flit_is = c;
		flit_is := recv;
	}
	
	before intf.recv {
		assert flit_is = recv;
	}
	
	before intf.reset {
		assert flit_is = recv;
		flit_is := *;
		assume flit_is ~= recv;
	}
	
} #end spec

